apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "rack-display.labels" . | nindent 4 }}
spec:
  selector: {{- include "rack-display.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
